### ISSUE TITLE
Редактирование задач (выделение циклов)

### ISSUE THREAD

**Issue by mmuddy** [mmuddy/taskgraph#8]

**Comment by mmuddy** [comment]
Redmine не позволяет организовывать циклические зависимости между задачами, возможно, прочие трекеры также не позволяют их организовывать. Имеется в виду, что данный фронтенд также должен отслеживать наличие циклов? Данный пункт имеет отношение к редактированию?

**Comment by zmm** [comment]
Данный пункт не имеет отношение к редактированию - он про статический анализ графа задач. 
Если такое ограничение есть в task трекерах, то думаю, что данную функциональность можно не делать.
