### ISSUE TITLE
Редактирование задач (изменение иерархической структуры)

### ISSUE THREAD

**Issue by mmuddy** [mmuddy/taskgraph#9]
Необходимо реализовать возможность редактирования иерархической структуры(представляется через отношение родительская/дочерняя задача):
- создания группы дочерних задач,
- создание родительской задачи для группы задач

/\* Не совсем понятно как осуществить определение недокомпозированной задачи. По правилу трех сигм?
Предполагается разделение недокомпозированной задачи на группу небольших? */

**Comment by TatyanaBerlenko** [comment]
Пользователь сам определяет, что задача недекомпозирована и инструмент должен предоставлять возможность ее "разбить" - создать подзадачи и настроить связи между ними.
